<div class="h-full w-full overflow-auto p-2">
  <h2 class="mb-2 font-bold">Task Description</h2>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
  <p class="mb-20">Write a function that returns the factorial of a number.</p>
</div>
