name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and push Docker image, run migrations, deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/n2t-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/n2t-web:${{ github.sha }}
          platforms: linux/amd64

      - name: Run DB migrations (for now just -help to test if image is available)
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/n2t-web:latest -help

      - name: Deploy to production
        run: echo "Deploying to production..."
